//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_HotelAndFlight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_DetailBooking
    {
        public int Id { get; set; }
        public Nullable<int> HF_BookingID { get; set; }
        public string Name { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> Date_flight { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public Nullable<int> F_CouponID { get; set; }
        public Nullable<int> F_Maskapai_FlightclassID { get; set; }
        public string Status { get; set; }
    
        public virtual F_Coupon F_Coupon { get; set; }
        public virtual HF_Booking HF_Booking { get; set; }
        public virtual F_Maskapai_Flightclass F_Maskapai_Flightclass { get; set; }
    }
}
