//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_HotelAndFlight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Flightclass_Facility
    {
        public int Id { get; set; }
        public Nullable<int> F_FacilityID { get; set; }
        public Nullable<int> F_FlightclassID { get; set; }
    
        public virtual F_Facility F_Facility { get; set; }
        public virtual F_Flightclass F_Flightclass { get; set; }
    }
}
