//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_HotelAndFlight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Detailbooking
    {
        public int Id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> Checkin_date { get; set; }
        public Nullable<System.DateTime> Checkout_date { get; set; }
        public Nullable<int> HF_BookingID { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public Nullable<int> H_Hotel_RoomtypeID { get; set; }
        public string Status { get; set; }
    
        public virtual H_Hotel_Roomtype H_Hotel_Roomtype { get; set; }
        public virtual HF_Booking HF_Booking { get; set; }
    }
}
