//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_HotelAndFlight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Hotel_Roomtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public H_Hotel_Roomtype()
        {
            this.H_Detailbooking = new HashSet<H_Detailbooking>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Available { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> H_RoomtypeID { get; set; }
        public Nullable<int> H_HotelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<H_Detailbooking> H_Detailbooking { get; set; }
        public virtual H_Hotel H_Hotel { get; set; }
        public virtual H_Roomtype H_Roomtype { get; set; }
    }
}
