//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_HotelAndFlight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Roomtype
    {
        internal object H_RoomtypeID;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public H_Roomtype()
        {
            this.H_Hotel_Roomtype = new HashSet<H_Hotel_Roomtype>();
            this.H_Roomtype_Facility = new HashSet<H_Roomtype_Facility>();
        }
    
        public int Id { get; set; }
        public string Roomtype_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<H_Hotel_Roomtype> H_Hotel_Roomtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<H_Roomtype_Facility> H_Roomtype_Facility { get; set; }
    }
}
