//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_HotelAndFlight.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Flight_ReservationEntities5 : DbContext
    {
        public Flight_ReservationEntities5()
            : base("name=Flight_ReservationEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<F_Airport> F_Airport { get; set; }
        public virtual DbSet<F_Coupon> F_Coupon { get; set; }
        public virtual DbSet<F_DetailBooking> F_DetailBooking { get; set; }
        public virtual DbSet<F_Facility> F_Facility { get; set; }
        public virtual DbSet<F_Flightclass> F_Flightclass { get; set; }
        public virtual DbSet<F_Flightclass_Facility> F_Flightclass_Facility { get; set; }
        public virtual DbSet<F_Maskapai> F_Maskapai { get; set; }
        public virtual DbSet<F_Maskapai_Flightclass> F_Maskapai_Flightclass { get; set; }
        public virtual DbSet<H_Detailbooking> H_Detailbooking { get; set; }
        public virtual DbSet<H_Facility> H_Facility { get; set; }
        public virtual DbSet<H_Hotel> H_Hotel { get; set; }
        public virtual DbSet<H_Hotel_Roomtype> H_Hotel_Roomtype { get; set; }
        public virtual DbSet<H_Roomtype> H_Roomtype { get; set; }
        public virtual DbSet<H_Roomtype_Facility> H_Roomtype_Facility { get; set; }
        public virtual DbSet<HF_Payment> HF_Payment { get; set; }
        public virtual DbSet<HF_User> HF_User { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<regency> regencies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<village> villages { get; set; }
    }
}
